#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
IoServe CLI

Runs ioflo plan from command line shell

example production:

ioserve -v concise -r -p 0.0625 -n ioserve -f ../ioserve/flo/plan/main.flo -b ioserve.core


example testing:

ioserve -v concise -r -p 0.0625 -n ioserve -f ../ioserve/flo/plan/test.flo -b ioserve.core

"""
import sys
import ioflo.app.run

def main():
    """ Main entry point for ioserve CLI"""
    from ioserve import __version__
    args = ioflo.app.run.parseArgs(version=__version__)  # inject  version here

    ioflo.app.run.run(  name=args.name,
                        period=float(args.period),
                        real=args.realtime,
                        retro=args.retrograde,
                        filepath=args.filename,
                        behaviors=args.behaviors,
                        mode=args.parsemode,
                        username=args.username,
                        password=args.password,
                        verbose=args.verbose,
                        consolepath=args.console,
                        statistics=args.statistics)

if __name__ == '__main__':
    main()
